
name : Multishop

description : |
    Makes working with multiple Shopify stores easier.

inputs:

    Secret:
        description : SSH Secret
        required : true

    Staging:
        description : Description
        required : true

    Stable:
        description : Description
        required : true

    Commit:
        description : Description
        required : true

    Email:
        description : Description
        required : true

    User:
        description : Description
        required : true

    Paths:
        description : Description
        required : true

runs:

    using : composite

    steps:

        -   name : Checkout Staging Repository
            uses : actions/checkout@v3
            with :

                repository : ${{ github.repository }}
                ssh-key : ${{ inputs.Secret }}
                ref : ${{ inputs.Staging }}

        -   name : Set Git Account
            shell : bash
            run : |
                "${{ github.action_path }}/Source/User.sh"  \
                "${{ inputs.Email }}"                       \
                "${{ inputs.User }}"

        -   name : Fetch Origin
            shell : bash
            run : |
                git fetch origin                            \
                ${{ inputs.Stable }}:${{ inputs.Stable }}   \
                --update-head-ok

        -   name : Transfer Relevant Changes
            shell : bash
            run : |
                "${{ github.action_path }}/Source/Transfer.sh"  \
                "${{ inputs.Staging }}"                         \
                "${{ inputs.Stable }}"                          \
                "${{ inputs.Paths }}"

        -   name : Status
            shell : bash
            run : git status

        -   name : Commit Changes
            shell : bash
            run : |
                "${{ github.action_path }}/Source/Commit.sh" \
                "${{ inputs.Commit }}"
