
name : Multishop

description : |
    Makes working with multiple Shopify stores easier.

runs:
    using : node20
    main : dist/index.js

inputs:

    Secret:
        description : SSH Secret
        required : true

    Config:
        description : Configuration
        required : true
